# Generated by Django 5.1.3 on 2024-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_moviereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonreviewdata',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
