# Generated by Django 5.1.3 on 2024-12-13 12:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_gamereview_tvreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonreviewdata',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
