# Generated by Django 5.1.3 on 2024-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('quiet_room', models.BooleanField()),
                ('price_per_night', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
        ),
    ]
