# Generated by Django 5.1.3 on 2024-12-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
